version: "3.8"

networks:
    static-site:

services:
    pelican:
        build:
            context: ./pelican
            args:
                - VERSION=${PYTHON_VERSION}
        networks:
            - static-site
        ports:
            - "8000:8000"
        volumes:
            - ./:/home/blog

    webpack:
        build:
            context: ./webpack
            args:
                - VERSION=${NODE_VERSION}
        networks:
            - static-site
        volumes:
            - ./:/home/blog

